config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  before_create :generate_access_token

  private
    def generate_access_token
      begin
        self.access_token = SecureRandom.hex
      end while self.class.exists?(access_token: access_token)
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :restrict_access
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:word, :definition)
    end

    def restrict_access
      authenticate_or_request_with_http_token do |token, options|
        ApiKey.exists?(access_token: token)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.erb
<%= form_for(dictionary) do |f| %>
  <% if dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
      <% dictionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :definition %>
    <%= f.text_field :definition %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<h1>Editing Dictionary</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionaries</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.word %></td>
        <td><%= dictionary.definition %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dictionary', new_dictionary_path %>

app/views/dictionaries/new.html.erb
<h1>New Dictionary</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Back', dictionaries_path %>

app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @dictionary.word %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @dictionary.definition %>
</p>

<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KhmerDict</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>